import os
import numpy as np
import tensorflow as tf
import sys
sys.path.append('../') 
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
from utils.utils import *


# del_here
op_0 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/edbtjc.so')
op_1 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/hoizdc.so')
op_2 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/nqqjou.so')
op_3 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/vgayej.so')
op_4 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/swujal.so')
op_5 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/trvsyc.so')
op_6 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/krubxg.so')
op_7 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/ridyvk.so')
op_8 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/ksuvcu.so')
op_9 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/vuwktm.so')
op_10 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/ffgwhz.so')
op_11 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/pfoxdt.so')
op_12 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/rfatdy.so')
op_13 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/zzdthb.so')
op_14 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/rhzgtx.so')
op_15 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/onoewg.so')
op_16 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/muonzn.so')
op_17 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/roiqtm.so')
op_18 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/ltzetc.so')
op_19 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/xzmump.so')
op_20 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/ucxfby.so')
op_21 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/oaaarp.so')
op_22 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/iultcl.so')
op_23 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/zuyfnk.so')
op_24 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/iwbbzk.so')
op_25 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/armxef.so')
op_26 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/qryjse.so')
op_27 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/mxxkvx.so')
op_28 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/zbkqal.so')
op_29 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/aoarcw.so')
op_30 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/akxxbp.so')
op_31 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/chkbaq.so')
op_32 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/scsxyt.so')
op_33 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/mqakbr.so')
op_34 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/bdtrdq.so')
op_35 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/hkpbpl.so')
op_36 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/lupfqk.so')
op_37 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/xzyluz.so')
op_38 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/pcglvk.so')
op_39 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/jnksmt.so')
op_40 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/ypqupw.so')
op_41 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/jwccof.so')
op_42 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/ntzvpn.so')
op_43 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/ejffeb.so')
op_44 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/fhjrrx.so')
op_45 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/jbnsvd.so')
op_46 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/bslysy.so')
op_47 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/rwcupn.so')
op_48 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/rojzwg.so')
op_49 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/roxnoc.so')
op_50 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/soqgci.so')
op_51 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/pwrqfn.so')
op_52 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/uhcexj.so')
op_53 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/opelxe.so')
op_54 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/aowezw.so')
op_55 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/tfsipc.so')
op_56 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/nggdzo.so')
op_57 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/lllbah.so')
op_58 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/cxntaj.so')
op_59 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/gfecce.so')
op_60 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/vlhsfg.so')
op_61 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/rvpejz.so')
op_62 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/gnhbls.so')
op_63 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/ngukpo.so')
op_64 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/tcaqmi.so')
op_65 = tf.load_op_library('/data/mingyi/code/obf_tf/obfop/tf_output_file/oosslm.so')
# add the so file above

class my_model(tf.Module):
    @tf.function
    def __call__(self, x):
# del_here
        out_0 = x
        out_3 = op_0.edbtjc(out_0)
        out_90 = op_1.hoizdc(out_3)
        out_16 = op_2.nqqjou(out_90)
        out_10 = op_3.vgayej(out_16)
        out_13 = op_4.swujal(out_16)
        out_8 = op_5.trvsyc(out_10, out_13)
        out_26 = op_6.krubxg(out_8)
        out_131 = op_42.ntzvpn(out_90)
        out_136 = op_46.bslysy(out_26)
        out_141 = op_50.soqgci(out_16)
        out_146 = op_55.tfsipc(out_3)
        out_152 = op_59.gfecce(out_3)
        out_23 = op_8.ksuvcu(out_26, out_152)
        out_148 = op_56.nggdzo(out_23)
        out_154 = op_61.rvpejz(out_16)
        out_20 = op_7.ridyvk(out_26, out_154)
        out_18 = op_9.vuwktm(out_20, out_23)
        out_129 = op_40.ypqupw(out_18)
        out_138 = op_48.rojzwg(out_20)
        out_157 = op_64.tcaqmi(out_18)
        out_158 = op_65.oosslm(out_10)
        out_36 = op_10.ffgwhz(out_18, out_3, out_158)
        out_30 = op_11.pfoxdt(out_36, out_146)
        out_33 = op_12.rfatdy(out_36)
        out_28 = op_13.zzdthb(out_30, out_33)
        out_91 = op_14.rhzgtx(out_28, out_138)
        out_46 = op_15.onoewg(out_91, out_91)
        out_40 = op_16.muonzn(out_46, out_46)
        out_43 = op_17.roiqtm(out_46)
        out_38 = op_18.ltzetc(out_40, out_43)
        out_130 = op_41.jwccof(out_40)
        out_132 = op_43.ejffeb(out_36)
        out_133 = op_44.fhjrrx(out_33)
        out_56 = op_19.xzmump(out_38, out_132, out_133)
        out_50 = op_20.ucxfby(out_56, out_23)
        out_53 = op_21.oaaarp(out_56, out_50, out_38)
        out_48 = op_22.iultcl(out_50, out_53)
        out_66 = op_23.zuyfnk(out_48, out_23)
        out_60 = op_24.iwbbzk(out_66, out_20)
        out_63 = op_25.armxef(out_66, out_131, out_136, out_148)
        out_58 = op_26.qryjse(out_60, out_63)
        out_76 = op_27.mxxkvx(out_58, out_157)
        out_70 = op_28.zbkqal(out_76, out_129)
        out_73 = op_29.aoarcw(out_76, out_76, out_40, out_30)
        out_68 = op_30.akxxbp(out_70, out_73)
        out_92 = op_31.chkbaq(out_68, out_48, out_26)
        out_86 = op_32.scsxyt(out_92, out_141)
        out_134 = op_45.jbnsvd(out_60)
        out_140 = op_49.roxnoc(out_50)
        out_143 = op_52.uhcexj(out_73)
        out_80 = op_33.mqakbr(out_86, out_8, out_140, out_143)
        out_144 = op_53.opelxe(out_40)
        out_145 = op_54.aowezw(out_92)
        out_149 = op_57.lllbah(out_66)
        out_151 = op_58.cxntaj(out_70)
        out_153 = op_60.vlhsfg(out_66)
        out_155 = op_62.gnhbls(out_28)
        out_156 = op_63.ngukpo(out_36)
        out_83 = op_34.bdtrdq(out_86, out_3, out_30, out_151, out_153, out_155, out_156)
        out_78 = op_35.hkpbpl(out_80, out_83)
        out_6 = op_36.lupfqk(out_78, out_63, out_60, out_144)
        out_137 = op_47.rwcupn(out_78)
        out_142 = op_51.pwrqfn(out_6)
        out_1 = op_37.xzyluz(out_6, out_130, out_134, out_142, out_145)
        out_88 = op_38.pcglvk(out_1, out_28, out_149)
        out_93 = op_39.jnksmt(out_88, out_10, out_137)
        return out_93
# add the data flow above

def create_model(x):
#     model=my_model()
#     model(x)
    model=my_model()
    concrete_func = model.__call__.get_concrete_function(x)
    converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func],
                                                                model)
    converter.allow_custom_ops = True
    tflite_model = converter.convert()
    with open('obf_model.tflite', 'wb') as f:
        f.write(tflite_model)